######################################################################
# Automatically generated by qmake (3.0) jeu. mai 4 16:15:21 2017
######################################################################

TEMPLATE = app
TARGET = cgal_test
INCLUDEPATH += .
INCLUDEPATH += $$PWD/include/

# Input
HEADERS += include/_kiss_fft_guts.h \
           include/fastexp.h \
           include/header.h \
           include/hex.h \
           include/hex_bitmaps.h \
           include/hex_cmd.h \
           include/hex_cmplx.h \
           include/hex_cuda.h \
           include/hex_cuda_drvapi.h \
           include/hex_cuda_rtapi.h \
           include/hex_dft.h \
           include/hex_dock.h \
           include/hex_dx.h \
           include/hex_fft.h \
           include/hex_fnmatch.h \
           include/hex_geom.h \
           include/hex_gl.h \
           include/hex_gl_dummy.h \
           include/hex_gmp.h \
           include/hex_gui.h \
           include/hex_hexlib.h \
           include/hex_main.h \
           include/hex_math.h \
           include/hex_mol.h \
           include/hex_molecule.h \
           include/hex_multipole.h \
           include/hex_pdb.h \
           include/hex_piper.h \
           include/hex_progress.h \
           include/hex_roc.h \
           include/hex_sdf.h \
           include/hex_sys.h \
           include/hex_thread.h \
           include/hex_transform.h \
           include/hex_types.h \
           include/hex_units.h \
           include/hex_util.h \
           include/hex_version.h \
           include/hex_widgets.h \
           include/hex_zlm.h \
           include/kids.h \
           include/kiss_fft.h
SOURCES += src/hex_pdb.cpp \
    src/main.cpp
